### ISSUE TITLE
ebtables-legacy segfauls on s390x with SLE15-SP2

### ISSUE THREAD

**Issue by thehejik** [k3s-io/k3s-root#45]
I just took binaries from ~https://github.com/k3s-io/k3s-root/releases/download/v0.10.0-rc.0/k3s-root-xtables-s390x.tar~ https://github.com/k3s-io/k3s-root/releases/download/v0.10.0-rc.0/k3s-root-s390x.tar and executed on s390x VM with SLE15-SP2:

```
./bin/aux/ebtables-legacy
Segmentation fault (core dumped)
```

kernel info:
```
sles@rancher-sles15sp2-jeos-ext4-devnet:~/k3s-root-release/k3s-root> uname -a
Linux rancher-sles15sp2-jeos-ext4-devnet 5.3.18-24.43-default #1 SMP Thu Dec 3 21:53:21 UTC 2020 (b48bf35) s390x s390x s390x GNU/Linux
```

just help:
```
strace ./bin/aux/ebtables-legacy --help
execve("./bin/aux/ebtables-legacy", ["./bin/aux/ebtables-legacy", "--help"], 0x3ffc307f3f8 /* 49 vars */) = 0
set_tid_address(0x10187d0)              = 29685
brk(NULL)                               = 0x2fef000
brk(0x2ff1000)                          = 0x2ff1000
mmap(0x2fef000, 4096, PROT_NONE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x2fef000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x3ff948fd000
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=NULL} ---
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault (core dumped)
```
and list tables:
```
strace -f ./ebtables-legacy -L
execve("./ebtables-legacy", ["./ebtables-legacy", "-L"], 0x3ffe7cfe910 /* 45 vars */) = 0
set_tid_address(0x10187d0)              = 29793
brk(NULL)                               = 0x2fba000
brk(0x2fbc000)                          = 0x2fbc000
mmap(0x2fba000, 4096, PROT_NONE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x2fba000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x3ff9befd000
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=NULL} ---
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault (core dumped)

**Comment by dweomer** [comment]
@manuelbuil @raulcabello did we decide if we cared about ebtables for s390x?

**Comment by raulcabello** [comment]
@dweomer if it is not used in rke2 we can remove it. What do you think @manuelbuil ?

**Comment by manuelbuil** [comment]
> @dweomer if it is not used in rke2 we can remove it. What do you think @manuelbuil ?

We should verify this. The general suspicion is that it was included just in case but we are not using it. However, nobody is 100% sure about it

**Comment by raulcabello** [comment]
we will find out if there are any issues with this while doing QA for s390x. I'll also try to find any reference to ebtables, but I could not find any until now.

**Comment by dweomer** [comment]
I don't like the idea of leaving a segfaulting footgun laying around but if we are not using it for rke2 let's make sure we elide it from the rke2 runtime and we can then nervously leave it here as a "known" issue.

**Comment by raulcabello** [comment]
That make sense. Is it possible to not generate ebtables binary in buildroot just for s390x?

**Comment by raulcabello** [comment]
@dweomer please have a look to have a look to https://github.com/k3s-io/k3s-root/pull/48

**Comment by dweomer** [comment]
Slack convo with @raulcabello and @manuelbuil:
> Jacob Blain Christen  29 minutes ago
> btw, **ebtables-legacy --help segfaults for me on x86_64**. this might be expected behavior without the backing ebtablesd running? (edited) 

> Raul Cabello  24 minutes ago
> I don't know, but then it looks like it is not an issue with s390x. I started ebtablesd on s390x, and ebtables-legacy still crashes

> Jacob Blain Christen  6 minutes ago
> **i think we just dont even know how to smoke test it** so if it seems unused lets just leave it alone for now

> Raul Cabello  3 minutes ago
> ok, then we'll use https://github.com/k3s-io/k3s-root/releases/tag/v0.10.0-rc.2 for now. I'll submit PRs to use it (we are using v0.10.-0-rc.0) and I will close https://github.com/k3s-io/k3s-root/pull/48
> #48 Do not generate ebtables for s390x
> <https://github.com/k3s-io/k3s-root|k3s-io/k3s-root>k3s-io/k3s-root | Today at 4:29 AM | Added by GitHub
