### ISSUE TITLE
Including k3s-root in vanilla buildroot build?

### ISSUE THREAD

**Issue by tuupola** [k3s-io/k3s-root#57]
What is the preferred way of including k3s-root in Buildroot built Linux image? I imagine building the k3s-root separately and adding the produced binaries using `BR2_ROOTFS_OVERLAY` is one option. Is there a better way?

**Comment by PiotrBzdrega** [comment]
> What is the preferred way of including k3s-root in Buildroot built Linux image? I imagine building the k3s-root separately and adding the produced binaries using `BR2_ROOTFS_OVERLAY` is one option. Is there a better way?
@tuupola were you able to append k3s agent to buildroot image in some other way ?
