### ISSUE TITLE
Crun support?

### ISSUE THREAD

**Issue by gytis-ivaskevicius** [k3s-io/k3s-root#58]
It would be cool if k3s supported crun https://github.com/containers/crun

**Comment by brandond** [comment]
You're welcome to install it on your nodes and provide a containerd.toml.tmpl ([as covered in the docs](https://docs.k3s.io/advanced#configuring-containerd)) that replaces runc with crun or makes it available as a RuntimeClass, but we're not planning on packaging it as an available runtime and/or replacing it as the default.
