### ISSUE TITLE
False positives triggering on VirusTotal

### ISSUE THREAD

**Issue by Supanutw** [k3s-io/k3s-root#63]
![SCR-25670327-qajg](https://github.com/k3s-io/k3s-root/assets/15275171/726568d5-0c2b-42c8-b321-229664133537)

**Comment by cwayne18** [comment]
This is a false positive were aware of and have already reached out to virustotal to correct.

**Comment by brandond** [comment]
Duplicate of https://github.com/k3s-io/k3s/issues/9738
